AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Users Service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        REGION: eu-west-1
  Api:
    OpenApiVersion: 3.0.1
    Cors: "'*'"

Parameters:
  Stage:
    Description: "Environment to deploy"
    Type: String
    Default: dev

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub users-api-gateway-${Stage}
      StageName: !Ref Stage

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub users-${Stage}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3

  UsersAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub users-api-${Stage}
      # PackageType: Image
      CodeUri: api/
      Handler: api
      Runtime: go1.x
      Tracing: Active
      Events:
        AllEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref ApiGatewayApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Environment:
        Variables:
          USERS_TABLE: !Sub users-${Stage}
    # Metadata:
    #   DockerTag: go1.x-v1
    #   DockerContext: ./
    #   Dockerfile: Dockerfile_api

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UsersAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/Users/"
  UsersFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt UsersAPIFunction.Arn
  UsersFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UsersAPIFunction.Arn
